/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jatmika (https://sketchfab.com/jatmika)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/home-aa0308fb68304716b60d4ba250e10589
title: Home
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function House(props) {
  const { nodes, materials } = useGLTF('/home.glb')

  const ref = useRef()

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    ref.current.rotation.x = THREE.MathUtils.lerp(ref.current.rotation.x, Math.cos(t) / 4 + 0.25, 0.1)
    ref.current.rotation.y = THREE.MathUtils.lerp(ref.current.rotation.y, Math.sin(t) / 4 - 10, 0.1)
    ref.current.rotation.z = THREE.MathUtils.lerp(ref.current.rotation.z, Math.sin(t) / 4, 0.1)
    ref.current.position.y = THREE.MathUtils.lerp(ref.current.position.y, (-50 + Math.sin(t / 2)) / 2, 0.1)
  })


  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[22.1, 1.84, 0]} rotation={[0, Math.PI / 2, 0]}>
          <group position={[0, -1.84, -22.1]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
          </group>
        </group>
        <group position={[-67.76, 0, 65.95]}>
          <group position={[67.76, 0, -65.95]}>
            <mesh geometry={nodes.Object_7.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[87.65, 27.81, 107.22]}>
          <group position={[-87.65, -27.81, -107.22]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[-15.77, 86.46, 65.95]} rotation={[0, 0, Math.PI / 2]}>
          <group position={[-86.46, -15.77, -65.95]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_13.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[6.87, -77.25, 65.95]} rotation={[0, 0, Math.PI / 2]}>
          <group position={[77.25, 6.87, -65.95]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_16.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[6.96, 53.15, 162.31]} rotation={[0.87, 0, Math.PI / 2]}>
          <group position={[-158.5, 6.96, -63.61]} rotation={[0, 0.87, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_19.geometry} material={materials['Mat.2']} />
          </group>
        </group>
        <group position={[6.96, -45.36, 161.39]} rotation={[2.27, 0, Math.PI / 2]}>
          <group position={[-152.79, 6.96, 68.99]} rotation={[-Math.PI, 0.87, Math.PI / 2]}>
            <mesh geometry={nodes.Object_22.geometry} material={materials['Mat.2']} />
          </group>
        </group>
        <group position={[22.1, 1.84, -4.07]} rotation={[0, Math.PI / 2, 0]}>
          <group position={[-4.07, -1.84, -22.1]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_25.geometry} material={materials.material_0} />
          </group>
        </group>
        <group position={[-41.75, 54.83, 186.94]}>
          <group position={[41.75, -54.83, -186.94]}>
            <mesh geometry={nodes.Object_28.geometry} material={materials.material} />
          </group>
        </group>
        <group position={[81.75, 0, 65.95]}>
          <group position={[-81.75, 0, -65.95]}>
            <mesh geometry={nodes.Object_31.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[71.81, 92.47, 66.83]} rotation={[0, 0, Math.PI / 2]}>
          <group position={[-92.47, 71.81, -66.83]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_34.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[82.66, 59.63, 81.33]} rotation={[0, 0, Math.PI / 2]}>
          <group position={[-59.63, 82.66, -81.33]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_37.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[95.95, 73.51, 67.71]}>
          <group position={[-95.95, -73.51, -67.71]}>
            <mesh geometry={nodes.Object_40.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[87.97, -33.99, 107.22]}>
          <group position={[-87.97, 33.99, -107.22]}>
            <mesh geometry={nodes.Object_43.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[51.45, 1.84, -4.07]} rotation={[0, Math.PI / 2, 0]}>
          <group position={[-4.07, -1.84, -51.45]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_46.geometry} material={materials.material_0} />
          </group>
        </group>
        <group position={[71.86, -40.4, 53.66]} rotation={[-Math.PI / 2, 0.77, Math.PI / 2]}>
          <group position={[53.66, 79.76, -20.85]} rotation={[0.8, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_49.geometry} material={materials['Mat.1']} />
          </group>
        </group>
        <group position={[85.54, 27.93, 62.27]} rotation={[0, Math.PI / 2, 0]}>
          <group position={[62.27, -27.93, -85.54]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_52.geometry} material={materials['Mat.1']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
